sequenceDiagram
activate RTI
activate ApplicationSimulator

RTI ->> ApplicationSimulator: VehicleRegistration
ApplicationSimulator ->> Application1: onStartup()
activate Application1
ApplicationSimulator ->> Application2: onStartup()
activate Application2

RTI ->> ApplicationSimulator: VehicleUpdates
ApplicationSimulator ->> Application1: onVehicleUpdated()
ApplicationSimulator ->> Application2: onVehicleUpdated()

RTI ->> ApplicationSimulator: VehicleUpdates
ApplicationSimulator ->> Application1: onVehicleUpdated()
ApplicationSimulator ->> Application2: onVehicleUpdated()
Application2 ->> ApplicationSimulator: sendV2xMessage()
ApplicationSimulator ->> RTI: V2xMessageTransmission

RTI ->> ApplicationSimulator: V2xMessageReceiption
ApplicationSimulator ->> Application1: onMessageReceived()

RTI ->> ApplicationSimulator: VehicleUpdates (remove)
ApplicationSimulator ->> Application1: onShutdown()
deactivate Application1
ApplicationSimulator ->> Application2: onShutdown()
deactivate Application2
